#!/bin/bash

MOTIVATIONAL_TEXT="$1"
TITLE_TEXT="$2"
FOOTER_TEXT="$3"
LUISCORREIAOPSGITHUB="$4"

INDEX_FILE="index.html"
MOTIVATIONAL_PLACEHOLDER="HOLDER" 
TITLE_PLACEHOLDER="__TITULO__"
FOOTER_PLACEHOLDER="__CONTRAPE__"
GITHUB_PLACEHOLDER="__LUISCORREIAOPSGITHUB__"

WRAPPED_TEXT="<p class=\"motivational-paragraph\">$MOTIVATIONAL_TEXT</p>"
echo "$WRAPPED_TEXT" > motivational_text.tmp

sed -i -e "/$MOTIVATIONAL_PLACEHOLDER/r motivational_text.tmp" -e "/$MOTIVATIONAL_PLACEHOLDER/d" "$INDEX_FILE"
rm motivational_text.tmp

sed -i "s|$TITLE_PLACEHOLDER|$TITLE_TEXT|g" "$INDEX_FILE"
sed -i "s|$FOOTER_PLACEHOLDER|$FOOTER_TEXT|g" "$INDEX_FILE"
sed -i "s|$GITHUB_PLACEHOLDER|$LUISCORREIAOPSGITHUB|g" "$INDEX_FILE"

echo "index.html atualizado."