#!/bin/bash

MOTIVATIONAL_TEXT="$1"
TITLE_TEXT="$2"
FOOTER_TEXT="$3"
LUISCORREIAOPSGITHUB="$4"


TEMPLATE_FILE="index.html"
OUTPUT_DIR="_site"
OUTPUT_FILE="$OUTPUT_DIR/index.html"
ESCOLHA_SH="#!/bin/bash"

MOTIVATIONAL_PLACEHOLDER="__HOLDER__"
TITLE_PLACEHOLDER="__TITULO__"
FOOTER_PLACEHOLDER="__CONTRAPE__"
GITHUB_PLACEHOLDER="__LUISCORREIAOPSGITHUB__"
SH_PLACEHOLDER="__SH__"

mkdir -p "$OUTPUT_DIR"
cp "$TEMPLATE_FILE" "$OUTPUT_FILE"

sed -i "s|$MOTIVATIONAL_PLACEHOLDER|$MOTIVATIONAL_TEXT|g" "$OUTPUT_FILE"
sed -i "s|$TITLE_PLACEHOLDER|$TITLE_TEXT|g" "$OUTPUT_FILE"
sed -i "s|$FOOTER_PLACEHOLDER|$FOOTER_TEXT|g" "$OUTPUT_FILE"
sed -i "s|$GITHUB_PLACEHOLDER|$LUISCORREIAOPSGITHUB|g" "$OUTPUT_FILE"
sed -i "s|$SH_PLACEHOLDER|$ESCOLHA_SH|g" "$OUTPUT_FILE"

echo "Arquivo $OUTPUT_FILE"