name: Conteudo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar Texto da API
        id: get_text
        env:
          API_PROMPT: ${{ secrets.API_PROMPT }}
        run: |
          API_KEY=${{ secrets.IA_API_KEY }}
          
          JSON_PAYLOAD=$(jq -n \
            --arg model "llama3-8b-8192" \
            --arg prompt "$API_PROMPT" \
            '{model: $model, messages: [{role: "user", content: $prompt}]}')
            
          RESPONSE=$(curl --fail-with-body -s -X POST https://api.groq.com/openai/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d "$JSON_PAYLOAD")
          
          TEXT_CONTENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          if [ -z "$TEXT_CONTENT" ]; then
            TEXT_CONTENT="Could not retrieve text, but the workflow is running!"
          fi
          echo "text_content<<EOF" >> $GITHUB_OUTPUT
          echo "$TEXT_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Construir HTML
        env:
          PAGE_TITLE: ${{ secrets.PAGE_TITLE }}
          PAGE_FOOTER: ${{ secrets.PAGE_FOOTER }}
          LUISCORREIAOPSGITHUB: ${{ secrets.LUISCORREIAOPSGITHUB }}
        run: |
          chmod +x .github/scripts/update_html.sh
          bash .github/scripts/update_html.sh \
            "${{ steps.get_text.outputs.text_content }}" \
            "$PAGE_TITLE" \
            "$PAGE_FOOTER" \
            "$LUISCORREIAOPSGITHUB"
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

  deploy:
    needs: build
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4