name: Conteudo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar Texto da API
        id: get_text
        run: |
          API_KEY=${{ secrets.IA_API_KEY }}
          RESPONSE=$(curl --fail-with-body -s -X POST https://api.groq.com/openai/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d '{
              "model": "llama3-8b-8192",
              "messages": [{"role": "user", "content": "Generate a single paragraph of encouraging text about technology or programming. Do not include any title, preamble, or introductory sentence. Provide only the paragraph itself no more than 5 lines."}]
            }')
          
          TEXT_CONTENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          if [ -z "$TEXT_CONTENT" ]; then
            TEXT_CONTENT="Could not retrieve text, but the workflow is running!"
          fi
          echo "text_content<<EOF" >> $GITHUB_OUTPUT
          echo "$TEXT_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Atualizar Pagina HTML
        run: |
          chmod +x .github/scripts/update_html.sh
          bash .github/scripts/update_html.sh "${{ steps.get_text.outputs.text_content }}"

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Keep Developing: Update motivational text"
            git push origin main
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4